#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Wed Apr 11 13:16:48 2018
#

import wx
import gettext
import sys
from pyo import *
from random import uniform
pm_list_devices()

###Changer la lignes suivante en fonction de la position dans votre machine
sys.path.insert(0, '/home/vincent/Documents/univ/hiver2018/mus3325/git/MUS3325X/app')
####


sys.path.insert(0, sys.path[0]+'/GUI')
sys.path.insert(0, sys.path[1]+'/Synth')
import gui2
import synth

a = synth.Synth(0)
gui2.run(a)
a.exit()