#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Thu Apr 12 17:36:55 2018
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame2(wx.Frame):
    def __init__(self, synth, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        wx.Frame.__init__(self, *args, **kwds)
        self.label_1 = wx.StaticText(self, wx.ID_ANY, _("Select instrument"))
        self.combo_box_1 = wx.ComboBox(self, wx.ID_ANY, choices=[_("defaut"), _("sinein")], style=wx.CB_DROPDOWN)
        self.button_2 = wx.Button(self, wx.ID_ANY, _("add effect"))
        self.button_3 = wx.Button(self, wx.ID_ANY, _("remove effect"))
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Run"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.effet1, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.effet2, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.start, self.button_1)
        # end wxGlade
        self.activated=False
        self.effect=[]
        self.synth=synth
    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle(_("frame_3"))
        self.combo_box_1.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.label_1, 0, 0, 0)
        sizer_4.Add(self.combo_box_1, 0, 0, 0)
        sizer_4.Add(self.button_2, 0, 0, 0)
        sizer_4.Add(self.button_3, 0, 0, 0)
        sizer_3.Add(sizer_4, 1, 0, 0)
        sizer_3.Add(self.button_1, 0, 0, 0)
        sizer_2.Add(sizer_3, 1, 0, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        self.Layout()
        # end wxGlade    
    def start(self, event):  # wxGlade: MyFrame2.<event_handler>
        if not self.activated:
            self.synth.start(self.combo_box_1.GetStringSelection())
            self.activated=True
        else:
            self.synth.stop()
            self.activated=False
        event.Skip()
    
    def effet1(self, event):
        self.synth.addEffect("Disto")
        added=False
        index = 0
        while(not added):
            tmp = "disto" + index
            if tmp in self.effect :
                index +=1
            else:
                self.effect.append(tmp)
                added = True
        print(self.effect)

    def effet2(self, event):
        
        event.Skip()
# end of class MyFrame2

def run(synth):
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp()
    frame_3 = MyFrame2(synth,None, wx.ID_ANY, "")
    app.SetTopWindow(frame_3)
    frame_3.Show()
    app.MainLoop()
    








